### PR TITLE
fix compile error

### PR DESCRIPTION
**Pull request by agnauck**
current source is not compiling. This fixes the compile

### CODE REVIEW

**Comment by guusdk** [comment]
How do you reproduce the problem that this PR is addressing? 

This commit adds a property named `atrributes`, which seems to be a typo of `attributes` - is that intended?

**Comment by agnauck** [comment]
its a type, thanks. Pushed a commit to address it.

**Comment by guusdk** [comment]
Hi Alex - I'm sorry to confuse everyone, but I now think that the typo is neccesary.

This is being reported by the compile step: note that it complains about missing a property _with that typo_:
```
##[group]Run npm run compile
[36;1mnpm run compile[0m
shell: /usr/bin/bash -e {0}
##[endgroup]

> stanza@12.18.0 compile /home/runner/work/stanza/stanza
> tsc -p .

##[error]src/jingle/sdp/Protocol.ts(330,55): error TS2345: Argument of type '{ direction: JingleApplicationDirection; id: number; uri: string; }' is not assignable to parameter of type 'SDPHeaderExtension'.
  Property 'atrributes' is missing in type '{ direction: JingleApplicationDirection; id: number; uri: string; }' but required in type 'SDPHeaderExtension'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! stanza@12.18.0 compile: `tsc -p .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the stanza@12.18.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2023-09-28T07_00_55_338Z-debug.log
##[error]Process completed with exit code 2.
```

**Comment by agnauck** [comment]
I can take a look later today when I have some time. It was a while back when I created this fix.
It was reported in the stanza Muc room that the code does not compile, and at this this was the fix to me.
I would need to research where the `atrributes` are defined and coming from.

**Comment by agnauck** [comment]
Took a quick look. 
This is how its defined in the sdp node module:

```
export interface SDPHeaderExtension {
    id: number;
    direction?: SDPDirection;
    uri: string;
    atrributes: string | undefined;
}
```

will revert my change.

**Pull request merged**
